# Generated by Django 4.1.3 on 2022-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='username',
            field=models.CharField(default='user', max_length=20, verbose_name='Имя пользователя'),
        ),
    ]
