# Generated by Django 4.1.3 on 2022-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_alter_virtualmachine_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ['time_create'], 'verbose_name': 'Виртуальные машины', 'verbose_name_plural': 'Виртуальные машины'},
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='running',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
