# Generated by Django 4.1.3 on 2022-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_alter_virtualmachine_options_virtualmachine_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='ssh_key',
            field=models.CharField(default='', max_length=500, verbose_name='SSH-ключ'),
        ),
    ]
