# Generated by Django 4.1.3 on 2022-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_alter_virtualmachine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='ssh_key',
            field=models.CharField(max_length=500, verbose_name='SSH-ключ'),
        ),
    ]
