# Generated by Django 4.1.3 on 2022-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_alter_virtualmachine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='running',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Активна'),
        ),
    ]
