# Generated by Django 4.1.3 on 2022-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0006_alter_virtualmachine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='boot_disk_size',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Размер диска'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='cores',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='vCPU'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='running',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Активна'),
        ),
    ]
