# Generated by Django 4.1.3 on 2022-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0007_alter_virtualmachine_boot_disk_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='running',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
