# Generated by Django 4.1.3 on 2022-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0008_alter_virtualmachine_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='core_fraction',
            field=models.PositiveSmallIntegerField(choices=[(20, '20%'), (50, '50%'), (100, '100%')], default=20, verbose_name='Гарантированная доля vCPU'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memory',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='RAM'),
        ),
    ]
