# Generated by Django 4.1.3 on 2022-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0009_alter_virtualmachine_core_fraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='core_fraction',
            field=models.PositiveSmallIntegerField(choices=[(5, '5%'), (20, '20%'), (100, '100%')], default=20, verbose_name='Гарантированная доля vCPU'),
        ),
    ]
